name: com_3gtt_jsxw
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.17.1 <3.0.0'
dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  intl_generator: ^0.2.1
  r_dart_library: 0.4.0-nullsafety.0
  json_serializable: ^6.2.0
  build_runner: ^2.1.11
  json_annotation: ^4.5.0
  get: ^4.6.5
  logger: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_1.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_10.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_101.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_102.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_103.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_104.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_105.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_106.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_107.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_108.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_11.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_12.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_13.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_14.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_15.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_16.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_2.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_3.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_4.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_5.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_6.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_7.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_8.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_9.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_all.png
  - packages/com_3gtt_jsxw/assets/images/tabbar/tabbar_1.png
  - packages/com_3gtt_jsxw/assets/images/tabbar/tabbar_2.png
  - packages/com_3gtt_jsxw/assets/images/tabbar/tabbar_3.png
  - packages/com_3gtt_jsxw/assets/images/tabbar/tabbar_4.png
  - packages/com_3gtt_jsxw/assets/images/tabbar/tabbar_5.png
  - packages/com_3gtt_jsxw/assets/texts/weapons_home.json
flutter_intl:
  enabled: true
flr:
  core_version: 3.2.0
  dartfmt_line_length: 80
  assets:
  - lib/assets/images
  - lib/assets/texts
  fonts:
  - lib/assets/fonts
