include: package:lints/recommended.yaml
name: com_3gtt_jsxw
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.17.1 <3.0.0'
dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  intl_generator: ^0.2.1
  r_dart_library: 0.4.0-nullsafety.0
  json_serializable: ^6.2.0
  build_runner: ^2.1.11
  json_annotation: ^4.5.0
  get: ^4.6.5
  logger: ^1.1.0
  dio: ^4.0.6
  pull_to_refresh: ^2.0.0
  screenshot: ^1.2.3
  path_provider: ^2.0.11
  share_plus: ^4.0.7
  image_gallery_saver: ^1.7.1
  webview_flutter: ^3.0.4
  cached_network_image: ^3.2.1
  date_format: ^2.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
  - packages/com_3gtt_jsxw/assets/images/arsenal/arsenal1.jpeg
  - packages/com_3gtt_jsxw/assets/images/arsenal/arsenal2.jpeg
  - packages/com_3gtt_jsxw/assets/images/arsenal/arsenal3.jpeg
  - packages/com_3gtt_jsxw/assets/images/arsenal/arsenal4.jpeg
  - packages/com_3gtt_jsxw/assets/images/arsenal/arsenal5.jpeg
  - packages/com_3gtt_jsxw/assets/images/arsenal/arsenal6.jpeg
  - packages/com_3gtt_jsxw/assets/images/arsenal/arsenal7.jpeg
  - packages/com_3gtt_jsxw/assets/images/arsenal/arsenal8.jpeg
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_1.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_10.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_101.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_102.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_103.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_104.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_105.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_106.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_107.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_108.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_11.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_12.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_13.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_14.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_15.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_16.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_2.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_3.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_4.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_5.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_6.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_7.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_8.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_9.png
  - packages/com_3gtt_jsxw/assets/images/arsenal/icon_all.png
  - packages/com_3gtt_jsxw/assets/images/country/america_s.png
  - packages/com_3gtt_jsxw/assets/images/country/argentina_s.png
  - packages/com_3gtt_jsxw/assets/images/country/australia_s.png
  - packages/com_3gtt_jsxw/assets/images/country/austria_s.png
  - packages/com_3gtt_jsxw/assets/images/country/belgium_s.png
  - packages/com_3gtt_jsxw/assets/images/country/bosnia_and_herzegovina_s.png
  - packages/com_3gtt_jsxw/assets/images/country/brazil_s.png
  - packages/com_3gtt_jsxw/assets/images/country/bulgaria_s.png
  - packages/com_3gtt_jsxw/assets/images/country/canada_s.png
  - packages/com_3gtt_jsxw/assets/images/country/chile_s.png
  - packages/com_3gtt_jsxw/assets/images/country/china_s.png
  - packages/com_3gtt_jsxw/assets/images/country/croatia_s.png
  - packages/com_3gtt_jsxw/assets/images/country/czech_s.png
  - packages/com_3gtt_jsxw/assets/images/country/denmark_s.png
  - packages/com_3gtt_jsxw/assets/images/country/egypt_s.png
  - packages/com_3gtt_jsxw/assets/images/country/europeanunion_s.png
  - packages/com_3gtt_jsxw/assets/images/country/finland_s.png
  - packages/com_3gtt_jsxw/assets/images/country/france_s.png
  - packages/com_3gtt_jsxw/assets/images/country/germany_s.png
  - packages/com_3gtt_jsxw/assets/images/country/greece_s.png
  - packages/com_3gtt_jsxw/assets/images/country/hungary_s.png
  - packages/com_3gtt_jsxw/assets/images/country/india_s.png
  - packages/com_3gtt_jsxw/assets/images/country/indonesia_s.png
  - packages/com_3gtt_jsxw/assets/images/country/iran_s.png
  - packages/com_3gtt_jsxw/assets/images/country/iraq_s.png
  - packages/com_3gtt_jsxw/assets/images/country/ireland_s.png
  - packages/com_3gtt_jsxw/assets/images/country/israel_s.png
  - packages/com_3gtt_jsxw/assets/images/country/italy_s.png
  - packages/com_3gtt_jsxw/assets/images/country/japan_s.png
  - packages/com_3gtt_jsxw/assets/images/country/jordan_s.png
  - packages/com_3gtt_jsxw/assets/images/country/kazakhstan_s.png
  - packages/com_3gtt_jsxw/assets/images/country/korea_s.png
  - packages/com_3gtt_jsxw/assets/images/country/luxembourg_s.png
  - packages/com_3gtt_jsxw/assets/images/country/malaysia_s.png
  - packages/com_3gtt_jsxw/assets/images/country/mexico_s.png
  - packages/com_3gtt_jsxw/assets/images/country/myanmar_s.png
  - packages/com_3gtt_jsxw/assets/images/country/netherlands_s.png
  - packages/com_3gtt_jsxw/assets/images/country/new_zealand_s.png
  - packages/com_3gtt_jsxw/assets/images/country/north_korea_s.png
  - packages/com_3gtt_jsxw/assets/images/country/norway_s.png
  - packages/com_3gtt_jsxw/assets/images/country/pakistan_s.png
  - packages/com_3gtt_jsxw/assets/images/country/panama_s.png
  - packages/com_3gtt_jsxw/assets/images/country/peru_s.png
  - packages/com_3gtt_jsxw/assets/images/country/poland_s.png
  - packages/com_3gtt_jsxw/assets/images/country/portugal_s.png
  - packages/com_3gtt_jsxw/assets/images/country/romania_s.png
  - packages/com_3gtt_jsxw/assets/images/country/russia_s.png
  - packages/com_3gtt_jsxw/assets/images/country/serbia_s.png
  - packages/com_3gtt_jsxw/assets/images/country/singapore_s.png
  - packages/com_3gtt_jsxw/assets/images/country/slovakia_s.png
  - packages/com_3gtt_jsxw/assets/images/country/south_africa_s.png
  - packages/com_3gtt_jsxw/assets/images/country/spain_s.png
  - packages/com_3gtt_jsxw/assets/images/country/sweden_s.png
  - packages/com_3gtt_jsxw/assets/images/country/switzerland_s.png
  - packages/com_3gtt_jsxw/assets/images/country/thailand_s.png
  - packages/com_3gtt_jsxw/assets/images/country/the_united_arab_emirates_s.png
  - packages/com_3gtt_jsxw/assets/images/country/turkey_s.png
  - packages/com_3gtt_jsxw/assets/images/country/ukraine_s.png
  - packages/com_3gtt_jsxw/assets/images/country/united_kingdom_s.png
  - packages/com_3gtt_jsxw/assets/images/country/vietnam_s.png
  - packages/com_3gtt_jsxw/assets/images/lcweb_forword.png
  - packages/com_3gtt_jsxw/assets/images/more/mine_apps.png
  - packages/com_3gtt_jsxw/assets/images/more/mine_download.png
  - packages/com_3gtt_jsxw/assets/images/more/mine_mark.png
  - packages/com_3gtt_jsxw/assets/images/more/mine_pro.png
  - packages/com_3gtt_jsxw/assets/images/more/mine_restore.png
  - packages/com_3gtt_jsxw/assets/images/more/mine_review.png
  - packages/com_3gtt_jsxw/assets/images/more/mine_share.png
  - packages/com_3gtt_jsxw/assets/images/more/mine_upgrade.png
  - packages/com_3gtt_jsxw/assets/images/navigationbar/navi_collect.png
  - packages/com_3gtt_jsxw/assets/images/navigationbar/navi_collect_select.png
  - packages/com_3gtt_jsxw/assets/images/navigationbar/navi_more.png
  - packages/com_3gtt_jsxw/assets/images/tabbar/tabbar_1.png
  - packages/com_3gtt_jsxw/assets/images/tabbar/tabbar_2.png
  - packages/com_3gtt_jsxw/assets/images/tabbar/tabbar_3.png
  - packages/com_3gtt_jsxw/assets/images/tabbar/tabbar_4.png
  - packages/com_3gtt_jsxw/assets/images/tabbar/tabbar_5.png
  - packages/com_3gtt_jsxw/assets/texts/aircraft.json
  - packages/com_3gtt_jsxw/assets/texts/arsenalTime.json
  - packages/com_3gtt_jsxw/assets/texts/arsenalmenu.json
  - packages/com_3gtt_jsxw/assets/texts/jshtml.json
  - packages/com_3gtt_jsxw/assets/texts/parameter.json
  - packages/com_3gtt_jsxw/assets/texts/ranklist.json
  - packages/com_3gtt_jsxw/assets/texts/testhtml.json
  - packages/com_3gtt_jsxw/assets/texts/weapons_home.json
  - packages/com_3gtt_jsxw/assets/texts/Aircraft.json
flutter_intl:
  enabled: true
flr:
  core_version: 3.2.0
  dartfmt_line_length: 80
  assets:
  - lib/assets/images
  - lib/assets/texts
  fonts:
  - lib/assets/fonts
linter:
  rules:
    non_constant_identifier_names: false
